version: '3'
services:
    jenkins:
        image: jenkins/docker
        build:
            context: dockerjenkins
        ports:
            - 7000:8080
            - 50000:50000
        container_name: jenkins 
        volumes:
            - $PWD/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - net
        restart: unless-stopped

    
    ubuntu_custom:
        image: ubuntu/docker
        build:
            context: docker_ubuntu
        container_name: ubuntu_uwu
        restart: unless-stopped    



networks:
    net:

